// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WoWArmory.Context;

#nullable disable

namespace WoWArmory.Migrations
{
    [DbContext(typeof(ArmoryDbContext))]
    partial class ArmoryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CharacterCommunity", b =>
                {
                    b.Property<Guid>("CharactersId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CommunitiesId")
                        .HasColumnType("uuid");

                    b.HasKey("CharactersId", "CommunitiesId");

                    b.HasIndex("CommunitiesId");

                    b.ToTable("CharacterCommunity");
                });

            modelBuilder.Entity("CharacterRaid", b =>
                {
                    b.Property<Guid>("CharactersId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RaidsId")
                        .HasColumnType("uuid");

                    b.HasKey("CharactersId", "RaidsId");

                    b.HasIndex("RaidsId");

                    b.ToTable("CharacterRaid");
                });

            modelBuilder.Entity("RaidUser", b =>
                {
                    b.Property<Guid>("RaidsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsersId")
                        .HasColumnType("uuid");

                    b.HasKey("RaidsId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("RaidUser");
                });

            modelBuilder.Entity("UserUserGroup", b =>
                {
                    b.Property<Guid>("UserGroupsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsersId")
                        .HasColumnType("uuid");

                    b.HasKey("UserGroupsId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("UserUserGroup");
                });

            modelBuilder.Entity("WoWArmory.Contracts.Models.Character", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AchievementPoints")
                        .HasColumnType("integer");

                    b.Property<string>("ActiveTitle")
                        .HasColumnType("text");

                    b.Property<int>("ArmoryId")
                        .HasColumnType("integer");

                    b.Property<int>("AverageItemLevel")
                        .HasColumnType("integer");

                    b.Property<int?>("CharacterClassId")
                        .HasColumnType("integer");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasComputedColumnSql("CASE WHEN \"ActiveTitle\" IS NOT NULL THEN regexp_replace(\"ActiveTitle\", '{name}', \"Name\") ELSE \"Name\" END", true);

                    b.Property<int>("EquippedItemLevel")
                        .HasColumnType("integer");

                    b.Property<int>("Experience")
                        .HasColumnType("integer");

                    b.Property<string>("Faction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("GuildId")
                        .HasColumnType("uuid");

                    b.Property<int?>("GuildRank")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("LastLoginTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("RaceId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("RealmId")
                        .HasColumnType("uuid");

                    b.Property<string>("RealmName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CharacterClassId");

                    b.HasIndex("GuildId");

                    b.HasIndex("RaceId");

                    b.HasIndex("RealmId");

                    b.HasIndex("UserId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("WoWArmory.Contracts.Models.CharacterClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameFr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CharacterClasses");
                });

            modelBuilder.Entity("WoWArmory.Contracts.Models.CharacterHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AchievementPoints")
                        .HasColumnType("integer");

                    b.Property<string>("ActiveTitle")
                        .HasColumnType("text");

                    b.Property<int>("ArmoryId")
                        .HasColumnType("integer");

                    b.Property<int>("AverageItemLevel")
                        .HasColumnType("integer");

                    b.Property<int?>("CharacterClassId")
                        .HasColumnType("integer");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasComputedColumnSql("CASE WHEN \"ActiveTitle\" IS NOT NULL THEN regexp_replace(\"ActiveTitle\", '{name}', \"Name\") ELSE \"Name\" END", true);

                    b.Property<int>("EquippedItemLevel")
                        .HasColumnType("integer");

                    b.Property<int>("Experience")
                        .HasColumnType("integer");

                    b.Property<string>("Faction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastLoginTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("RaceId")
                        .HasColumnType("integer");

                    b.Property<string>("RealmName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CharacterClassId");

                    b.HasIndex("CharacterId");

                    b.HasIndex("RaceId");

                    b.ToTable("CharacterHistories");
                });

            modelBuilder.Entity("WoWArmory.Contracts.Models.Community", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Communities");
                });

            modelBuilder.Entity("WoWArmory.Contracts.Models.EquippedItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("EnchantmentId")
                        .HasColumnType("integer");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<float>("Level")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Quality")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("Slot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("ItemId");

                    b.ToTable("EquippedItems");
                });

            modelBuilder.Entity("WoWArmory.Contracts.Models.Guild", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ArmoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("RealmId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Visible")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("RealmId");

                    b.ToTable("Guilds");
                });

            modelBuilder.Entity("WoWArmory.Contracts.Models.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsEquippable")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsStackable")
                        .HasColumnType("boolean");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("MaxCount")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("PurchasePrice")
                        .HasColumnType("bigint");

                    b.Property<int>("PurchaseQuantity")
                        .HasColumnType("integer");

                    b.Property<string>("Quality")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RequiredLevel")
                        .HasColumnType("integer");

                    b.Property<long>("SellPrice")
                        .HasColumnType("bigint");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("WoWArmory.Contracts.Models.MetaData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Key")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MetaDatas");
                });

            modelBuilder.Entity("WoWArmory.Contracts.Models.Race", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameFr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Races");
                });

            modelBuilder.Entity("WoWArmory.Contracts.Models.Raid", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("MinItemLevel")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RaidDay")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("RaidTime")
                        .HasColumnType("time without time zone");

                    b.HasKey("Id");

                    b.ToTable("Raids");
                });

            modelBuilder.Entity("WoWArmory.Contracts.Models.RaidLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RaidId")
                        .HasColumnType("uuid");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WarcraftLogsCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RaidId");

                    b.ToTable("RaidLogs");
                });

            modelBuilder.Entity("WoWArmory.Contracts.Models.Realm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DisplayNameEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DisplayNameFr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Realms");
                });

            modelBuilder.Entity("WoWArmory.Contracts.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<Guid>("MainCharacterId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MainGuildId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MainRaidId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WoWAccessToken")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WoWArmory.Contracts.Models.UserGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("UserGroups");
                });

            modelBuilder.Entity("CharacterCommunity", b =>
                {
                    b.HasOne("WoWArmory.Contracts.Models.Character", null)
                        .WithMany()
                        .HasForeignKey("CharactersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WoWArmory.Contracts.Models.Community", null)
                        .WithMany()
                        .HasForeignKey("CommunitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CharacterRaid", b =>
                {
                    b.HasOne("WoWArmory.Contracts.Models.Character", null)
                        .WithMany()
                        .HasForeignKey("CharactersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WoWArmory.Contracts.Models.Raid", null)
                        .WithMany()
                        .HasForeignKey("RaidsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RaidUser", b =>
                {
                    b.HasOne("WoWArmory.Contracts.Models.Raid", null)
                        .WithMany()
                        .HasForeignKey("RaidsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WoWArmory.Contracts.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UserUserGroup", b =>
                {
                    b.HasOne("WoWArmory.Contracts.Models.UserGroup", null)
                        .WithMany()
                        .HasForeignKey("UserGroupsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WoWArmory.Contracts.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WoWArmory.Contracts.Models.Character", b =>
                {
                    b.HasOne("WoWArmory.Contracts.Models.CharacterClass", "CharacterClass")
                        .WithMany("Characters")
                        .HasForeignKey("CharacterClassId");

                    b.HasOne("WoWArmory.Contracts.Models.Guild", "Guild")
                        .WithMany("Members")
                        .HasForeignKey("GuildId");

                    b.HasOne("WoWArmory.Contracts.Models.Race", "Race")
                        .WithMany("Characters")
                        .HasForeignKey("RaceId");

                    b.HasOne("WoWArmory.Contracts.Models.Realm", "Realm")
                        .WithMany("Characters")
                        .HasForeignKey("RealmId");

                    b.HasOne("WoWArmory.Contracts.Models.User", "User")
                        .WithMany("Characters")
                        .HasForeignKey("UserId");

                    b.Navigation("CharacterClass");

                    b.Navigation("Guild");

                    b.Navigation("Race");

                    b.Navigation("Realm");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WoWArmory.Contracts.Models.CharacterHistory", b =>
                {
                    b.HasOne("WoWArmory.Contracts.Models.CharacterClass", "CharacterClass")
                        .WithMany()
                        .HasForeignKey("CharacterClassId");

                    b.HasOne("WoWArmory.Contracts.Models.Character", "Character")
                        .WithMany("CharacterHistories")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WoWArmory.Contracts.Models.Race", "Race")
                        .WithMany()
                        .HasForeignKey("RaceId");

                    b.Navigation("Character");

                    b.Navigation("CharacterClass");

                    b.Navigation("Race");
                });

            modelBuilder.Entity("WoWArmory.Contracts.Models.EquippedItem", b =>
                {
                    b.HasOne("WoWArmory.Contracts.Models.Character", "Character")
                        .WithMany("EquippedItems")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WoWArmory.Contracts.Models.Item", "Item")
                        .WithMany("EquippedItems")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("WoWArmory.Contracts.Models.Guild", b =>
                {
                    b.HasOne("WoWArmory.Contracts.Models.Realm", "Realm")
                        .WithMany()
                        .HasForeignKey("RealmId");

                    b.Navigation("Realm");
                });

            modelBuilder.Entity("WoWArmory.Contracts.Models.RaidLog", b =>
                {
                    b.HasOne("WoWArmory.Contracts.Models.Raid", "Raid")
                        .WithMany("RaidLogs")
                        .HasForeignKey("RaidId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Raid");
                });

            modelBuilder.Entity("WoWArmory.Contracts.Models.Character", b =>
                {
                    b.Navigation("CharacterHistories");

                    b.Navigation("EquippedItems");
                });

            modelBuilder.Entity("WoWArmory.Contracts.Models.CharacterClass", b =>
                {
                    b.Navigation("Characters");
                });

            modelBuilder.Entity("WoWArmory.Contracts.Models.Guild", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("WoWArmory.Contracts.Models.Item", b =>
                {
                    b.Navigation("EquippedItems");
                });

            modelBuilder.Entity("WoWArmory.Contracts.Models.Race", b =>
                {
                    b.Navigation("Characters");
                });

            modelBuilder.Entity("WoWArmory.Contracts.Models.Raid", b =>
                {
                    b.Navigation("RaidLogs");
                });

            modelBuilder.Entity("WoWArmory.Contracts.Models.Realm", b =>
                {
                    b.Navigation("Characters");
                });

            modelBuilder.Entity("WoWArmory.Contracts.Models.User", b =>
                {
                    b.Navigation("Characters");
                });
#pragma warning restore 612, 618
        }
    }
}
